### ISSUE TITLE
The rossystem model generator should dump the parameters at the end

### ISSUE THREAD

**Issue by ipa-nhg** [ipa320/ros_model_parser#31]
probably we have just to move these code lines to the end https://github.com/ipa320/ros_model_parser/blob/master/src/ros_model_generator/rossystem_generator.py#L60

**Comment by ipa-hsd** [comment]
fixed in https://github.com/ipa320/ros_model_parser/pull/32
Also fixes generation of params https://github.com/jackal/jackal_robot/blob/noetic-devel/jackal_base/config/diagnostic_analyzers.yaml#L11-L16
