### ISSUE TITLE
rossystem parser fails for parameters

### ISSUE THREAD

**Issue by ipa-hsd** [ipa320/ros_model_parser#5]
For the [manipulation capability](https://github.com/ipa-nhg/ros-model-experiments/blob/7be7efd29abd7a09276e43f4ba10da3a39cef156/cob4-25/cob4-25_monitoring/cob4-25_manipualtion.rossystem) rossystem example, the parser fails for `RosParameter`. The parser [expects](https://github.com/ipa320/ros_model_parser/blob/4e4854be4cc60cad2b68f39528b290f911a0efc5/src/ros_model_parser/rossystem_parser.py#L127) the grammar to have `value` keyword.

**Comment by ipa-nhg** [comment]
Thanks for pointing this issue, there were actually 2 issues with this model:

```
RosSystem { Name 'cob4-25_manipulation_capability'
    RosComponents ( 
        ComponentInterface { name 'manipulation'
            RosPublishers {
                RosPublisher '/tf' {RefPublisher '...'}}
            RosSubscribers {
                RosSubscriber '/arm_right/joint_trajectory_controller/command' {RefSubscriber  '...'},
                RosSubscriber '/arm_left/joint_trajectory_controller/command' {RefSubscriber '...'}}
            RosParameters {
                RosParameter 'robot_description' { RefParameter "cob4.parameters_node.parameters_node./robot_description"}
            }}
)}
```

First, as you pointed, the parser expected the definition of a value for the RosParameter while for the Xtext grammar this is an optional [attribute](https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.rossystem.xtext/src/de/fraunhofer/ipa/rossystem/RosSystem.xtext#L135), the second issue I found is the use of double quotes for the reference (i.e.  RefParameter **"** cob4.parameters_node.parameters_node./robot_description **"**) this was also not allowed for the parser.

Both issues were fixed for the latest version of the parser: https://github.com/ipa320/ros_model_parser/pull/4/commits/fa2a6702c00c58e73c60170d182c0028141301ac
